#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

require( __DIR__ . '/vendor/autoload.php' ); // in yii2-dev repo
require( __DIR__ . '/vendor/yiisoft/yii2/Yii.php' );

$application = new yii\console\Application([
    'id' => 'yii-console',
    'basePath' => __DIR__ . '/console',
    'controllerNamespace' => 'yii\console\controllers',
    'components' => [
			'db' => require('config/db.php'),
	],
]);
$exitCode = $application->run();
exit($exitCode);
